CapaPresentacionTienda/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CapaEntidad;
using CapaNegocio;

using System.IO;
using System.Web.Services.Description;
using System.Threading.Tasks;
using System.Data;
using System.Globalization;
using System.Collections;

namespace CapaPresentacionTienda.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult DetalleProducto(int idproducto = 0)
        {
            bool conversion;
            var oProducto = new CnProducto().Listar().Find(p => p.IdProducto == idproducto);

            if (oProducto != null)
            {
                oProducto.Base64 = CnRecursos.ConvertirBase64(Path.Combine(oProducto.RutaImagen, oProducto.NombreImagen), out conversion);
                oProducto.Extension = Path.GetExtension(oProducto.NombreImagen);
            }

            return View(oProducto);
        }






        [HttpGet]
        public JsonResult ListaCategorias() {
            _ = new List<Categoria>();
            List<Categoria> lista = new CnCategoria().Listar();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarMarcaporCategoria(int idcategoria)
        {
            _ = new List<Marca>();
            List<Marca> lista = new CnMarca().ListarMarcaporCategoria(idcategoria);
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarProducto(int idcategoria, int idmarca)
        {
            bool conversion;

            var lista = new CnProducto().Listar().Select(p => new Producto()
            {
                IdProducto = p.IdProducto,
                Nombre = p.Nombre,
                Descripcion = p.Descripcion,
                oMarca = p.oMarca,
                oCategoria = p.oCategoria,
                Precio = p.Precio,
                Stock = p.Stock,
                RutaImagen = p.RutaImagen,
                Base64 = CnRecursos.ConvertirBase64(Path.Combine(p.RutaImagen, p.NombreImagen), out conversion),
                Extension = Path.GetExtension(p.NombreImagen),
                Activo = p.Activo
            }).Where(p =>
                p.oCategoria.IdCategoria == (idcategoria == 0 ? p.oCategoria.IdCategoria : idcategoria) &&
                p.oMarca.IdMarca == (idmarca == 0 ? p.oMarca.IdMarca : idmarca) &&
                p.Stock > 0 && p.Activo).ToList();

            var jsonresult = Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            jsonresult.MaxJsonLength = int.MaxValue;

            return jsonresult;
        }

        [HttpPost]
        public JsonResult AgregarCarrito(int idproducto)
        {

            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            bool existe = new CnCarrito().ExisteCarrito(idcliente, idproducto);
            bool respuesta = false;
            string mensaje  = string.Empty;
            if (existe)
            {
                mensaje = "El producto ya existe en el carrito";
            }
            else
            {
                respuesta = new CnCarrito().OperacionCarrito(idcliente, idproducto, true, out mensaje);
            }
            return Json(new {respuesta =respuesta, mensaje= mensaje },JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public JsonResult CantidadEnCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            int cantidad = new CnCarrito().CantidadEnCarrito(idcliente);
            return Json(new { cantidad =cantidad }, JsonRequestBehavior.AllowGet);


        }

        [HttpPost]
        public JsonResult ListarProductosCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool conversion;

            var oLista = new CnCarrito().ListarProducto(idcliente).Select(oc => new Carrito()
            {
                oProducto = new Producto()
                {
                    IdProducto = oc.oProducto.IdProducto,
                    Nombre = oc.oProducto.Nombre,
                    oMarca = oc.oProducto.oMarca,
                    Precio = oc.oProducto.Precio,
                    RutaImagen = oc.oProducto.RutaImagen,
                    Base64 = CnRecursos.ConvertirBase64(Path.Combine(oc.oProducto.RutaImagen, oc.oProducto.NombreImagen), out conversion),
                    Extension = Path.GetExtension(oc.oProducto.NombreImagen)
                },
                Cantidad = oc.Cantidad
            }).ToList();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

        public JsonResult OperacionCarrito(int idproducto,bool sumar)
        {

            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CnCarrito().OperacionCarrito(idcliente, idproducto, true, out mensaje);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult EliminarCarrito(int idproducto)
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CnCarrito().EliminarCarrito(idcliente, idproducto);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);


        }
        [HttpPost]
        public JsonResult ObtenerDepartamento()
        {
            var oLista = new CnUbicacion().ObtenerDepartamento();

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult ObtenerProvincia(string IdDepartamento)
        {
            var oLista = new CnUbicacion().ObtenerProvincia(IdDepartamento);
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]


        public JsonResult ObtenerDistrito(string IdDepartamento,string IdProvincia)
        {
            _ = new List<Distrito>();
            List<Distrito> oLista = new CnUbicacion().ObtenerDistrito(IdDepartamento, IdProvincia);
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Carrito()
        {

            return View();
        }

        [HttpPost]
        public Task<JsonResult> ProcesarPago(List<Carrito> oListaCarrito, Venta oVenta)
        {
            decimal total = 0;
            DataTable detalle_venta = new DataTable();
            detalle_venta.Locale = new CultureInfo("es-PE");
            detalle_venta.Columns.Add("IdProducto", typeof(string));
            detalle_venta.Columns.Add("Cantidad", typeof(int));
            detalle_venta.Columns.Add("Total", typeof(decimal));

            foreach (Carrito oCarrito in oListaCarrito)
            {
                decimal subtotal = Convert.ToDecimal(oCarrito.Cantidad.ToString()) * oCarrito.oProducto.Precio;
                total += subtotal;

                detalle_venta.Rows.Add(
                    oCarrito.oProducto.IdProducto,
                    oCarrito.Cantidad,
                    subtotal
                );
            }

            oVenta.MontoTotal = total;
            oVenta.IdCliente = ((Cliente)Session["Cliente"]).IdCliente;
            TempData["Venta"] = oVenta;
            TempData["DetalleVenta"] = detalle_venta;

            // Return a JsonResult asynchronously
            return Task.FromResult(Json(new { Status = true, Link = "/Tienda/PagoEfectuado?idTransaccion=code0001&status=true" }, JsonRequestBehavior.AllowGet));
        }

        public Task<ActionResult> PagoEfectuado()
        {

            string idtransaccion = Request.QueryString["idtransaccion"];
            bool status = Convert.ToBoolean(Request.QueryString["status"]);

            ViewData["Status"] = status;
            if (status)
            {

                Venta oVenta = (Venta)TempData["Venta"];
                DataTable detalle_venta = (DataTable)TempData["DetalleVenta"];
                oVenta.IdTransaccion = idtransaccion;
                string mensaje = string.Empty;
                _ = new CnVenta().Registrar(oVenta, detalle_venta, out mensaje);

                ViewData["IdTransaccion"] = oVenta.IdTransaccion;


            }
            return Task.FromResult<ActionResult>(View());


        }

    }
}

CapaPresentacionTienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Add Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        .navbar-custom {
            background-color: #1a1a1a; /* Color oscuro para la barra de navegación */
        }

            .navbar-custom .navbar-brand,
            .navbar-custom .nav-link,
            .navbar-custom .navbar-toggler-icon {
                color: #f8f9fa; /* Color claro para los enlaces y el icono de toggler */
            }

                .navbar-custom .nav-link.active {
                    color: #ffc107; /* Color dorado para el enlace activo */
                }

            .navbar-custom .btn-outline-dark {
                color: #f8f9fa;
                border-color: #f8f9fa;
            }

                .navbar-custom .btn-outline-dark:hover {
                    background-color: #f8f9fa;
                    color: #1a1a1a;
                }

        footer {
            background-color: #1a1a1a;
            color: #f8f9fa;
            padding: 1rem 0;
            text-align: center;
        }
    </style>
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-custom">
        <div class="container-fluid px-4">
            <a class="navbar-brand" href="#!">Mi tienda</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index","Tienda")">Inicio</a></li>
                    @*<li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>*@
                </ul>
                <form class="d-flex">
                    @if (Session["Cliente"] == null)
                    {
                        <a class="btn btn-outline-dark" aria-current="page" href="@Url.Action("Index", "Acceso")"><i class="fas fa-sign-out-alt me-1"></i>Iniciar Sesión</a>
                    }
                    else
                    {
                        <a class="btn btn-outline-dark" href="@Url.Action("Carrito","Tienda")">
                            <i class="fas fa-shopping-cart me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cantidadcarrito">0</span>
                        </a>
                        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#!"><b>@User.Identity.Name</b></a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("MisCompras","Tienda")">Mis Compras</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index","Acceso")">Cerrar Sesion</a></li>
                                </ul>
                            </li>
                        </ul>
                    }
                </form>
            </div>
        </div>
    </nav>
    @RenderBody()
    <footer>
        <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
    </footer>
    <!-- Add Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

<script>
        $(document).ready(function () {
            MostrarCantidadCarrito();
        });


        function MostrarCantidadCarrito() {
            if ($("#cantidadcarrito").length > 0) {

                jQuery.ajax({
                    url: '@Url.Action("CantidadEnCarrito", "Tienda")',
                    type: "GET",
                    //data: JSON.stringify(),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {


                        $("#cantidadcarrito").text(data.cantidad)

                    }




                });


            }

        }

</script>
</body>
</html>